package com.example.uas_masjid;

import java.util.ArrayList;

public class DataMasjid{
    public static String[][] data = new String[][]{
            {"Masjid Agung Palembang","Jl. Jend Sudirman, 19 Ilir, Kec. Bukit Kecil, Kota Palembang, Sumatera Selatan 30111\n"+
                    "Masjid Agung Palembang (Indonesia Masjid Agung Palembang), juga dikenal sebagai Masjid Agung Sultan Mahmud Badaruddin I setelah mantan Sultan Palembang, adalah masjid utama Palembang, ibukota Sumatera Selatan. Masjid ini merupakan masjid terbesar di Sumatera Selatan, dan masjid terbesar ketiga di Sumatera setelah Masjid Raya Sumatera Barat dan Masjid Agung Pekanbaru.", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Palembang_Grand_Mosque.jpg/800px-Palembang_Grand_Mosque.jpg", "-2.987895437710507, 104.76020555513554"},
            {"Masjid Cheng Ho","15 Ulu, Kecamatan Seberang Ulu I, Kota Palembang, Sumatera Selatan 30267\n"+
                    "Masjid Zheng He, secara resmi Masjid Islam Mohammed Zheng He di Sriwijayan Palembang (bahasa Indonesia: Masjid Al-Islamiyyah Muhammad Cheng Ho Sriwijaya Palembang), adalah sebuah masjid yang didedikasikan untuk umat Tionghoa Muslim yang terletak di Jakabaring Palembang, Sumatera Selatan, Indonesia. Nama masjid ini untuk menghormati Laksamana Cina Muslim yang terkenal, Zheng He. Masjid ini didirikan atas prakarsa para sesepuh, penasehat, pengurus Persatuan Islam Tionghoa Indonesia (PITI) Sumatera Selatan, serta tokoh masyarakat Tionghoa di sekitar Palembang. Sebelumnya masjid ini dipimpin oleh imam ternama, Ustadz Choirul Rizal yang telah hafal 30 juz' Alquran. Ustadz Miftah yang saat ini menjabat sebagai imam, juga seorang hafiz.","https://www.google.com/search?q=masjid+cheng+ho&&tbm=isch&ved=2ahUKEwiVxNL-veD8AhVFiNgFHTV-CZ0Q2-cCegQIABAA&oq=masjid+cheng&gs_lcp=CgNpbWcQARgAMgsIABCABBCxAxCDATIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoECCMQJzoGCAAQBxAeOgQIABBDOgcIABCxAxBDOggIABCABBCxAzoICAAQsQMQgwFQgAdYlRZg4CJoAHAAeACAAUiIAdsFkgECMTOYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=MfTPY9XnD8WQ4t4Ptfyl6Ak&bih=979&biw=1920#imgrc=pc7OkhKqKalRXM","-3.024343658869345, 104.78003921134093"},
            {"Masjid Lawang Kidul","Lorong Masjid, Lawang Kidul, Ilir Timur II, Palembang City, Sumatera Selatan 30118\n"+
                    "Masjid Lawang Kidul termasuk salah satu masjid tertua di Palembang, Sumatra Selatan. Masjid ini berdiri pada tahun 1881 dan memegang peran penting baik sebagai pusat penyebaran Islam maupun dijadikan markas para pejuang setempat pada masanya. Material Masjid ini terbuat dari campuran batu kapur dengan putih telur dan pasir, sehingga membuat masjid ini dapat bertahan dengan lama. Bangunan induk masjid ini sebagian besar tetap terjaga keasliannya dan hampir 99 persen masih merupakan bangunan asli dan belum ada yang diganti.","https://www.google.com/search?q=masjid+Lawang+kidul&tbm=isch&ved=2ahUKEwjxp5-xvuD8AhVyjNgFHbXuDBkQ2-cCegQIABAA&oq=masjid+Lawang+kidul&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEOgQIIxAnOgQIABAeOgYIABAIEB46BwgAEIAEEBhQxglY9Rxg4B5oAHAAeACAAY4BiAHLBpIBBDEyLjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=m_TPY7HuFvKY4t4Ptd2zyAE&bih=979&biw=1920#imgrc=aKyrWL0JNkNJvM","-2.9809242207431486, 104.77544902592278"},
            {"Masjid Al-Mahmudiyah Suro", "Jl. Ki Gede Ing Suro, Kelurahan 30 Ilir, Kecamatan Ilir Barat II, Palembang, Sumatera Selatan\n"+
                    "Masjid Besar Al-Mahmudiyah atau Masjid Suro adalah salah satu masjid tertua di kota Palembang.Dibangun oleh seorang ulama besar, KH Abdurahman Delamat (Ki Delamat) di atas tanah wakaf milik Kiai Kiagus H Khotib Mahmud tahun 1889 dan selesai tahun 1891. Masjid unik dengan ciri khas melayu ini, awalnya disebut dengan nama Masjid Suro. Lalu Kiagus H. Matjik Rosad, cucu dari Kiagus H Khotib Mahmud mengusulkan nama Al-Mahmudiyah, hingga akhirnya jadilah nama Al-Mahmudiyah.","https://www.google.com/search?q=Masjid+Al-Mahmudiyah+Suro&sxsrf=AJOqlzURLZiR42mg_tK_0qTopgYZqtH1tw:1674573073107&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj89bDpvuD8AhUr5XMBHeiTD0wQ_AUoAnoECAEQBA&biw=1920&bih=979&dpr=1#imgrc=WcJJlLTI-5ReCM","-2.9988713661898356, 104.7507248538172"},
            {"Masjid Kiai Muara Ogan","Jl. Kimarogan, Kertapati, Kec. Kertapati, Kota Palembang, Sumatera Selatan 30421\n"+
                    "Masjid Kiai Muara Ogan atau Masjid Ki Marogan adalah salah satu masjid tertua di Palembang, Sumatra Selatan. Masjid ini didirikan oleh Mgs. H. Abdul Hamid (Ki Marogan) seorang ulama Palembang yang sangat terkenal dan usahawan yang sukses pada tahun 1310 H atau 1890. Masjid Ki Marogan ini, merupakan masjid kedua yang dibangun di Palembang setelah Masjid Agung Palembang. Di masa Kesultanan Palembang masjid ini punya peran yang strategis dalam berbagai kegiatan keagamaan dan sosial masyarakat Palembang.","https://www.google.com/search?q=Masjid+Kiai+Muara+Ogan&&tbm=isch&ved=2ahUKEwjWiM3qvuD8AhVhDrcAHWikAvcQ2-cCegQIABAA&oq=Masjid+Kiai+Muara+Ogan&gs_lcp=CgNpbWcQAzIFCAAQgAQ6BAgjECdQngZYngZgqQ1oAHAAeACAATSIAWiSAQEymAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=E_XPY5azKOGc3LUP6MiKuA8&bih=979&biw=1920#imgrc=tIN9_2RNETu9CM","-3.01500107535432, 104.75001465506556"},
            {"Masjid Al-Aqobah 1 ","PT Pusri, Jl. Melur, Sei Selayur, Kec. Kalidoni, Kota Palembang, Sumatera Selatan 30118\n"+
                    "Masjid Al-Aqobah yang dibangun pada tahun 1994. Masjid Al-Aqobah merupakan kategori Masjid Umum. Masjid Al-Aqobah beralamat di Jl. Pupuk Raya Komp Perumahan Pusri Sako Palembang Sumatera Selatan . Masjid Al-Aqobah memiliki luas tanah 200 m2 , luas bangunan 300 m2 dengan status tanah Wakaf.","https://www.google.com/search?q=Masjid+Al-Aqobah+1+&&tbm=isch&ved=2ahUKEwjI7YH9vuD8AhUJKLcAHVbmALoQ2-cCegQIABAA&oq=Masjid+Al-Aqobah+1+&gs_lcp=CgNpbWcQAzoECCMQJ1DXBFjXBGDxCmgAcAB4AIABU4gBiQGSAQEymAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=OvXPY8joEInQ3LUP1syD0As&bih=979&biw=1920#imgrc=LyK35kXxbtCy5M","-2.9744976135599783, 104.79978260561474"},
            {"Masjid Al-Falah","Masjid Al Falah beralamat di Jl. Raja Wali RT. 26 Kel.9 Ilir Palembang Sumatera Selatan\n"+
                    "Masjid Al Falah yang dibangun pada 1969. Masjid Al Falah merupakan kategori Masjid Besar. Masjid Al Falah memiliki luas tanah 625 m2, luas bangunan 2.700 m2 dengan status tanah Wakaf. Masid Al Falah memiliki jumlah 50-100 orang, jumlah mazin 4 orang.","https://www.google.com/search?q=Masjid+Al-Falah&tbm=isch&ved=2ahUKEwjO15mKv-D8AhUfCrcAHRLmC-AQ2-cCegQIABAA&oq=Masjid+Al-Falah&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgQIABAeMgQIABAeUABYAGCEBWgAcAB4AIABQIgBQJIBATGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=VfXPY47ZOJ-U3LUPksyvgA4&bih=979&biw=1920#imgrc=vSd_ZpLIqP35dM","-2.974197397776744, 104.7640645719539"},
            {"Masjid Raya Taqwa","Jl. Ki Ranggo Eirosentiko RT.42 RW.14 Kelurahan 30 Ilir Kecamatan Ilir Barat II Palembang\n"+
                    "Masjid raya Taqwa Palembang merupakan salah satu masjid yang berdiri di tengah kota Palembang. Dekat dengan taman Kambang Iwak dan perumahan warga menjadikan masjid ini sebagai salah satu pusat kajian Islam kota Palembang. Masjid yang mampu menampung 1500 jamaah dan pernah terisi sampai 800-900 jamaah ini, memiliki pengurus berjumlah 75 orang, 7 orang imam beserta Khotib yang berjumlah 30 orang.  “Masjid ini didirikan pada masa H. Asnawi Mangku Alam sebagai gubernur Sumatera Selatan, tepatnya itu tahun 1973 ” ujar sekretaris pengurus masjid Taqwa Palembang Hamidin Nawawi.","https://www.google.com/search?q=Masjid+Raya+Taqwa&tbm=isch&ved=2ahUKEwj-sIqYv-D8AhUYktgFHdplCQcQ2-cCegQIABAA&oq=Masjid+Raya+Taqwa&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIGCAAQCBAeMgYIABAIEB4yBggAEAgQHjIGCAAQCBAeOgQIIxAnOgYIABAHEB46BAgAEB5Q3ANY3ANg9QhoAHAAeACAAUOIAXqSAQEymAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=c_XPY76rApik4t4P2sulOA&bih=979&biw=1920#imgrc=3-ZpgokvX9RhnM","-2.9884574125394914, 104.74314299832074"},
            {"Masjid Baitul Atiq","Jl. Merdeka, Telaga Semut, Kec. Bukit Kecil, Kota Palembang, Sumatera Selatan 30136\n"+
                    "Masjid Baitul Atiq merupakan masjid yang berada di Kota Palembang. Masjid ini menjadi tempat sholat dan beribadah ummat muslim disekitarnya yang rutin mendirikan sholat subuh berjamaah, dhuhur/zuhur, ashar, magrib dan isya. Masjid Baitul Atiq juga menjadi tujuan warga sekitar untuk menunaikan ibadah sunnah dan wajid dibulan Ramadhan seperti buka puasa bersama, sholat tarawih dan lainnya. Masjid di Kota Palembang ini juga dapat menyalurkan sumbangan, sedekah, kurban dan zakat warga Kota Palembang.","https://www.google.com/search?q=Masjid+Baitul+Atiq&tbm=isch&ved=2ahUKEwiG94etv-D8AhWBM7cAHYsKCtoQ2-cCegQIABAA&oq=Masjid+Baitul+Atiq&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgcIABCABBAYMgcIABCABBAYOgQIIxAnOgYIABAIEB5Q_AJY_AJgowhoAHAAeACAATmIAXCSAQEymAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=n_XPY8arAoHn3LUPi5Wo0A0&bih=979&biw=1920#imgrc=HM44vn_63j-EtM","-2.9893043337000957, 104.7490607813299"},
            {"Masjid Jami’ Istiqlal","Jl. Selingkeh Raya, Sako, Sialang, Kec. Sako, Kota Palembang, Sumatera Selatan 30961\n"+
                    "Masjid Jami’ Istiqlal yang dibangun pada tahun 1994. Masjid Jami’ Istiqlal merupakan kategori Masjid Umum. Masjid Jami’ Isqtiqlal memiliki luas tanah 300 m2, luas bangunan 400 m2 dengan status tanah Wakaf. Masjid Jami’ Istiqlal memiliki jumlah jamaah 150 – 200 orang, jumlah muazin 3 orang, jumlah remaja 30 orang dan jumlah Khotib 3 orang.","https://www.google.com/search?q=Masjid+Jami%E2%80%99+Istiqlal+palembang&tbm=isch&ved=2ahUKEwi3xvTOv-D8AhXf4XMBHWCCDioQ2-cCegQIABAA&oq=Masjid+Jami%E2%80%99+Istiqlal+palembang&gs_lcp=CgNpbWcQAzoECCMQJ1DDA1jqFGDcFWgAcAB4AIABfogB9wWSAQQxMC4xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=5vXPY7e7Ad_Dz7sP4IS60AI&bih=979&biw=1920#imgrc=xnpXdOe7Q-00WM","-2.93212609295066, 104.78237734435758"},
    };

    public static ArrayList<ModelMasjid> ambilDataMasjid(){
        ArrayList<ModelMasjid> dataMasjid = new ArrayList<>();

        for(String[] varData: data){
            ModelMasjid mdl = new ModelMasjid();
            mdl.setNama(varData[0]);
            mdl.setTentang(varData[1]);
            mdl.setFoto(varData[2]);
            mdl.setAlamat(varData[3]);
            mdl.setKoordinat(varData[4]);

            dataMasjid.add(mdl);
        }
        return dataMasjid;
    }
}